require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  NewCops: enable


Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - guard
Rails/ApplicationMailer:
  Enabled: false
Rails/Output:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'test/**/views/**/*.ruby'
