language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.6.x
notifications:
  email: true
before_script:
  - nvm install 10
  - npm install mjml
  - npm install promise
